### ISSUE TITLE
Currency hardcoded as AUD in StripeService.php 

### ISSUE THREAD

**Issue by dnrdigital** [mitydigital/statamic-stripe-checkout-fieldtype#1]
I'm in the UK. My Statamic locale is set to UK as described in your docs, and the field has GBP set as the currency. My Stripe account is also a GBP account. I get the following error from Stripe when using the fieldtype with a product:

> [13:57:47] LOG.error: StatamicStripeCheckout createCheckoutSession StripeService API Error: The price specified supports currencies of `aud` which doesn't include the expected currency of `gbp`.

This appears to be because 'AUD' is hardcoded at line [152 of StripeService.php](https://github.com/mitydigital/statamic-stripe-checkout-fieldtype/blob/main/src/Support/StripeService.php#L152):

```
'price_data' => [
    'currency' => 'AUD',
    ...
```

If I change this to 

```
'price_data' => [
    'currency' => $config->get('currency_code'),
    ...
```

it works as expected. I can submit as a PR if that's useful. BTW Thanks for this great addon - just scoping things out but will likely purchase for a client's production site as it's a huge timesaver :)

**Comment by martyf** [comment]
Totally my bad, sorry. I've fixed this up and released 1.0.1 which should address it.

Time saving is why we created it too: had the need for a few clients but just had to keep reminding ourselves of the scope: it's not an online store, but a hook in to Stripe for forms. Glad you're finding it useful!
