### ISSUE TITLE
Incorrect 'price-id' parameter in StripeService.php?

### ISSUE THREAD

**Issue by dnrdigital** [mitydigital/statamic-stripe-checkout-fieldtype#2]
I'm on the latest Stripe API ([2023-10-16](https://stripe.com/docs/upgrades#2023-10-16)). I get an error from stripe when using the the price option in the stripe checkout fieldset. Stripe says:

> Received unknown parameter: line_items[0][price_id]. Did you mean price?

If I change 'price_id' to 'price' at [line 139 of StripeService.php](https://github.com/mitydigital/statamic-stripe-checkout-fieldtype/blob/3ecac5eb04283576a4c9a8c84cc1809b64d8da06/src/Support/StripeService.php#L139) it seems to work:

```
  $lineItems[] = [
      'price' => $price['price_id'],
      'quantity' => $quantity,
  ];
```
Haven't fully tested with prices yet, so YMMV...

**Comment by martyf** [comment]
Thanks for raising this, and apologies for missing it. This has been resolved in 1.0.2.
